---
clone:
  depth: 50
  tags: true
  skip_verify: true

kind: pipeline
type: kubernetes
name: staging

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test

- name: publish tic-tac-toe
  image: plugins/docker
  depends_on: [build]
  settings:
    tags: "sta-latest"
    registry: docker.resolve.local:5000
    repo: docker.resolve.local:5000/tic-tac-toe
    insecure: true
  dry_run: true # remove this to publish

trigger:
  branch:
    include:
    - staging

---
clone:
  depth: 50
  tags: true
  skip_verify: true

kind: pipeline
type: kubernetes
name: production

steps:
- name: tag
  image: bashell/alpine-bash:latest
  depends_on: [clone]
  commands:
    - /bin/bash -c '[ -z $DRONE_TAG ] && echo "latest" || echo $DRONE_TAG'

- name: build
  image: node
  depends_on: [tag]
  commands:
  - npm install
  - npm test

- name: publish tic-tac-toe
  image: plugins/docker
  depends_on: [build]
  settings:
    tags: ${DRONE_TAG}
    registry: docker.resolve.local:5000
    repo: docker.resolve.local:5000/tic-tac-toe
    insecure: true
  dry_run: true # remove this to publish
  when:
    event:
      - tag

trigger:
  ref:
#  - refs/heads/master
  - refs/tags/**
